name: conduit_isolate_exec
version: 4.3.7
homepage: https://github.com/conduit-dart/isolate-exec
description: This library contains types that allow for executing code in a spawned isolate, perhaps with additional imports.
environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  analyzer: ^6.4.1
  glob: ^2.1.2
  path: ^1.9.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  test_package:
    path: ../isolate_exec_test_packages/test_package
