name: conduit_codable
version: 4.3.7
homepage: https://github.com/conduit-dart/conduit-codable
description: A serialization library for converting dynamic, structured data (JSON, YAML) into Dart types.
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  meta: ^1.12.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
