name: conduit_postgresql
description: The postgresql ORM for conduit.
version: 4.3.7
repository: https://github.com/conduit-dart/conduit

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  collection: ^1.18.0
  conduit_core: ^4.4.0
  postgres: ^2.6.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
