name: conduit_runtime
version: 4.3.7
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
repository: https://github.com/conduit-dart/conduit-runtime
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  conduit_isolate_exec: ^4.3.7
  io: ^1.0.4
  package_config: ^2.1.0
  path: ^1.9.0
  pubspec: ^2.3.0
  yaml: ^3.1.2
dev_dependencies:
  fs_test_agent:
    path: ../fs_test_agent
  lints: ^3.0.0
  test: ^1.25.2
