name: fs_test_agent
version: 4.3.7
homepage: https://stablekernel.com
description: Utilities for writing tests to validate file system and Dart project directory operations.
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  path: ^1.9.0
  pubspec: ^2.3.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
