name: conduit_test
version: 4.3.7
homepage: https://github.com/conduit-dart/conduit
description: Utilities for writing automated tests for Conduit applications
environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  test: ^1.25.2
  matcher: ^0.12.16+1
  conduit_core: ^4.3.8
dev_dependencies:
  conduit_postgresql:
    path: ../postgresql
  lints: ^3.0.0
  test_core: ^0.6.0
