name: conduit
version: 4.3.9
homepage: https://github.com/conduit-dart/conduit
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  collection: ^1.18.0
  conduit_common: ^4.3.7
  conduit_config: ^4.3.7
  conduit_core: ^4.3.8
  conduit_isolate_exec: ^4.3.7
  conduit_open_api: ^4.3.7
  conduit_password_hash: ^4.3.7
  conduit_postgresql: ^4.3.7
  conduit_runtime: ^4.3.7
  crypto: ^3.0.3
  io: ^1.0.4
  logging: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0
  postgres: ^2.6.3
  pub_semver: ^2.1.4
  yaml: ^3.1.2
dev_dependencies:
  conduit_test:
    path: ../test_harness
  fs_test_agent:
    path: ../fs_test_agent
  http: ^1.2.0
  lints: ^3.0.0
  matcher: ^0.12.16+1
  mockito: ^5.4.4
  test: ^1.25.2
  web_socket_channel: ^2.4.3
executables:
  conduit: conduit
