name: conduit_config
version: 4.3.7
description: A safe and convenient way to read YAML configuration files.
repository: https://github.com/conduit-dart/conduit-config.git
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  conduit_runtime: ^4.3.7
  meta: ^1.12.0
  yaml: ^3.1.2
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
